### ISSUE TITLE
question about Quickomics

### ISSUE THREAD

**Issue by fazeliniah** [interactivereport/Quickomics#1]
Thank you for developing this amazing tool. It seems very practical for our proteomics analysis. 
I had a quick question regarding creating the "Comparison Data" file: Is there any pipeline or script code you are recommending to generate the the "Comparison Data" file? This may also make a nice addition for Quickomics!
Thanks

**Comment by baohongz** [comment]
We use DESeq2 for RNAseq and limma for proteomics.
