### ISSUE TITLE
Strange p-value cutoff behavior on gene set enrichment

### ISSUE THREAD

**Issue by alexjacobsCDS** [interactivereport/Quickomics#3]
We're seeing some strange behavior using the p-value cutoff on the Gene Set Enrichment tab.  I'm not sure if maybe we're just confused about how this works.  Is the p-value cutoff using the same p-value that's displayed in the gene set enrichment table?  If so, I don't think it's working correctly.  See the attached screenshot where row 14,15 are on opposite sides of the 'p-value cutoff'.  If it's not using that p-value, what p-value is it using?  
<img width="1451" alt="Screen Shot 2021-07-23 at 2 11 46 PM" src="https://user-images.githubusercontent.com/48565768/126825075-5b5e590e-15c2-4311-b0fa-eb7526b5a1fd.png">

(this is using the demo mouse dataset included with the app)

Thanks!

**Comment by interactivereport** [comment]
The p-value or adj p-value cutoff is used to filter the gene/proteins  for geneset enrichment analysis, not the geneset enrichment p value. Geneset enrichment p-value is fixed at p < 0.05.

**Comment by alexjacobsCDS** [comment]
Understood, thank you!  Closing this issue
