### ISSUE TITLE
Getting disconnected from the server

### ISSUE THREAD

**Issue by MeghanaKB** [interactivereport/Quickomics#5]
Hello,

I am facing issues uploading the .RData file in quickomics. I have generated .RData file based on the given instructions. when I am trying to upload the file, it is automatically getting disconnected from the server. I also checked using .RData from the quickomics github, it shows the same error.

![image](https://user-images.githubusercontent.com/59667548/166731097-437c25c9-5c1b-49c6-8889-cdce8547bd0e.png)

would really appreciate if you can provide any inputs regarding this issue.

Best,
Meghana

**Comment by xinmin-zhang** [comment]
Hi Meghana, 
I think the issue might be that you didn't upload the network file, and the server somehow ran into issues when computing the network file form the Rdata file.  The network files for demo data is in networkdata folder. 
The easiest fix is for you to generate the network RData file. You can just choose the top genes if using all genes takes a long time and a lot of memory.  Or if you don't care about the correlation network tool, you can upload one of our demo network data (e.g. Mouse_microglia_RNA-Seq_network.RData) as the network file.
Hope this helps. 
Xinmin
