### ISSUE TITLE
Minimal sample number for a Quickomics project

### ISSUE THREAD

**Issue by sunyumail93** [interactivereport/Quickomics#6]
I prepared the four csv files (expression data, comparison, metadata, and an optional protein name file) and tried to upload them through the 'Upload Files' tab. Can I confirm with the team the minimal sample number required for a Quickomics project? For example, only two data in the Expression Data csv file seem not work. Thank you!

**Comment by xinmin-zhang** [comment]
For PCA and heatmap clustering, I suggest you have at least 3 samples.
