### ISSUE TITLE
Unable to load Geneset under 'Label genes' menu

### ISSUE THREAD

**Issue by vikrant577** [interactivereport/Quickomics#7]
Hello, I have been facing this issue since last 4 weeks. can someone please help me in this regard? Thank you.

**Comment by xinmin-zhang** [comment]
Please make sure you use https instead of http in the URL. The genset selection tool talks to API on another server, using http now causes CORS issue.

**Comment by vikrant577** [comment]
Thank you so much.


*Dr. Vikrant Palande*
Postdoctoral researcher
Charles University
Faculty of Pharmacy in Hradec Králové, Heyrovského 1203, 500 05 Hradec
Králové, Czech Republic.
Email: ***@***.***
