### ISSUE TITLE
GSEA

### ISSUE THREAD

**Issue by santoshdbhosale** [interactivereport/Quickomics#8]
Hello team,
Thank you for the amazing tool. I am using it for proteomics data analysis.
I am wondering how I can calculate the pathway enrichment based on the table.
Or should calculate the gene ratio based on the values reported in the table to see the pathway enrichment?
To get the gene ration, do I have to divide the DeGenNum with SetNum. I am not sure what SetNum means here and why this number is more than total number of DEGs in my case.
I am looking forward to your comments.
Thanks, Santosh

**Comment by xinmin-zhang** [comment]
Fold_Enrich has been added to ORA output. We also display SetNum (genes from the gene set that are in the dataset) and SetNumAll (genes from the gene set from genome, some of these genes may not present in the dataset) in the report.
